# -*- coding: utf-8 -*-
"""ms-marco-synthetic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZlxIexxl_T_3NfzA0dzW-YwAsAGRvqx-
"""

!pip install torch torchvision torchaudio
!pip install transformers
!pip install datasets

from datasets import load_dataset

dataset = load_dataset("ms_marco", 'v2.1')
print(dataset)

import pandas as pd

ms_marco = pd.DataFrame(dataset['train'])
ms_marco.head()

queries = ms_marco[['query', 'query_id']].copy()
queries.set_index('query_id', inplace=True)
queries.head()

temp = []

for index, row in ms_marco.iterrows():
    for key, value in row['passages'].items():
        temp.append({
            'passage_param': key,
            'passage_val': value,
            'query_id': row['query_id']
        })

temp_df = pd.DataFrame(temp)
temp_df.head(10)

print(temp_df["passage_val"].iloc[1])

passages_temp = []

for index, row in temp_df.iterrows():
    if row['passage_param'] == 'passage_text' and isinstance(row['passage_val'], list):
        for passage in row['passage_val']:
            passages_temp.append({
                'passage_param': row['passage_param'],
                'passage_val': passage,
                'query_id': row['query_id']
            })
    else:
        passages_temp.append(row.to_dict())

# Convert the expanded data back into a DataFrame
passages = pd.DataFrame(passages_temp)

passages.head(20)

passages.head(20)

